GET http://localhost:8100/api/shops HTTP/1.1

###
GET http://localhost:8100/api/shops/a3fcb9f9-6e8e-47da-89d8-0a2a12764a8e HTTP/1.1

###
POST http://localhost:8100/api/shops HTTP/1.1
Content-Type: application/json

{
    "name": "La cave de biyem assi",
    "description":"vente de spiritueux",
    "isOnCount":false,
    "isPaused":false
 
}

###

PATCH  http://localhost:8100/api/shops/a3fcb9f9-6e8e-47da-89d8-0a2a12764a8e HTTP/1.1
Content-Type: application/json

{
    "isPaused":true,
    "isOnCount":true
}
###

DELETE  http://localhost:8100/api/shops/7572e92e-b6e3-4da1-b414-8ca89b8c1019 HTTP/1.1
Content-Type: application/json


###
